### ISSUE TITLE
Inquiring about the process of pushing ABAP code from ADT to GitHub using ABAPGit

### ISSUE THREAD

**Issue by chunrichi** [workskong/ZI559461_DEMO#1]
Hi ，I am currently exploring the ABAPGit tool and its capabilities for version controlling ABAP code in SAP Train System.  I came across your have successfully push RAP code from ADT to Github using ABAPGit.

I use `Fine-grained personal access tokens`, But when i try to push and commit, it allways return http error of 401.

Can you tell me how to create the token for Sap RAP train system?

my token
![image](https://user-images.githubusercontent.com/28805901/228401006-73e875f2-b468-43d3-804e-5c47968508e9.png)

the return
![image](https://user-images.githubusercontent.com/28805901/228401055-f1ac5ab0-13db-4935-8ba9-1031d67aacb4.png)

**Comment by workskong** [comment]
You have to use Personal Access tokens.
![image](https://user-images.githubusercontent.com/59598285/228414627-b6ae8e83-763a-43de-8b5a-682c25f31637.png)

**Comment by chunrichi** [comment]
thank you so much, it usefull
